### PR TITLE
Feature/react 014

### PR DESCRIPTION
**Pull request by zachswansonlud**
Updating to use react 0.14 with no warnings; copying several changes from version on npm (0.70); resolved issue with frozen objects on Styled.js

### CODE REVIEW

**Comment by natew** [comment]
Really awesome. So glad someone finally dove in on this. @mbrookes have some time to test if this is working?

**Comment by mbrookes** [comment]
Hi guys, it's been quite a while since I've looked at reapp - I'm now fairly heavily involved in Material-UI, but happy to take this for a spin if you can tell me how to quickly test it.

**Comment by zachswansonlud** [comment]
The context of these changes was using just reapp-ui in a React project that is using browserify for its build process.  The main changes include
1.  Removing use of .getDOMElement and react-addons which getDomElement to work with newer versions of React without any warnings
2.  Modifying the styling aggregation to work with frozen objects (occurred when using a package to work with svg’s in browserify)
3.  Adding in a few changes found in the npm version that seem to break everything if not included

Not sure if this helps you or not as far as how to test but gives some context.

Thanks,

-Zach

**Comment by mbrookes** [comment]
I'm afraid I didn't keep any of my reapp experiments, and reapp-kit won't install. Sorry guys.

**Comment by natew** [comment]
Ah ok, sorry @mbrookes actually I meant to ping someone else whose been maintaining this!

**Comment by natew** [comment]
@jhopper28 ping

**Comment by natew** [comment]
For some reason on cloning this I see a ton of deleted files, like all the theme style files?

**Comment by jhopper28** [comment]
@natew I'm not seeing any deleted files :/

**Pull request merged**
