### PR TITLE
Update to React 0.14

### PR DESCRIPTION
**Pull request by Andreyco**

### CODE REVIEW

**Comment by Andreyco** [comment]
Hi there. I made some fixes to your codebase, ported it to support React 0.14.

Got it working, waiting for upstream in _reapp-raf-batching_ (under your control) and _react-style_ repositories.
Having npm3, you can get it working by depending on these packages in main repo

```
"dependencies": {
    "fbjs": "^0.4.0",
    "react": "^0.14.0",
    "react-style": "git+https://github.com/Andreyco/react-style.git#fix-react0.14",
    "reapp-raf-batching": "git+https://github.com/Andreyco/reapp-raf-batching.git",
    "reapp-ui": "{your tag after}"
  }
```

Sorry, I while merging, I made file mode changes by accident. Too lazy to revert.
I hope for merge. If you decide to, please, tag.
Needs some polishing (using react-addons-{addon} instead of react/addons), but some other people could help, starting with this.

**Comment by natew** [comment]
I was thinking this project would have a much much higher change of success if it was a mono-repo (like babel). Basically one repo, with all the dependencies as sub-folders. Allows a ton of cool stuff like having a nice makefile to automate a bunch of stuff.

Seems like everyone is too short on time and effort! But on a rainy day I'll give it a swing.

**Comment by natew** [comment]
Of course, any help is appreciated. I'd even support other people taking over reapp-raf (just change it to your repo or one that already works) and the other sub modules.

**Comment by natew** [comment]
Looks like a ton of stuff with files changing permissions? May have to try this again...

**Comment by Andreyco** [comment]
Agree with you, you should find balance between splitting or not splitting project into submodules. Where it makes sense, split.

Yes, a lot of file permissions changes. Do you want it back to 0644?

I will try to run codemod scripts from FB to migrate it to 0.14 completely.

**Comment by mbrookes** [comment]
@natew - Have you considered git submodules? Should have the same benefit as everything in one repo, while still allowing individual repos to be managed separately.

`git submodule add git://github.com/reapp/reapp-something.git [optional/sub/dir]`

**Pull request closed without merging**
