### PR TITLE
Added and corrected flexbox support, mostly for Safari.

### PR DESCRIPTION
**Pull request by jhopper28**
This fixes the issue where Safari would not stretch flexbox contained items. Also made a little correction to the README.

### CODE REVIEW

**Comment by natew** [comment]
We shouldn't need the Webkit stuff anymore with react-style-normalizer, right?

**Comment by jhopper28** [comment]
From what I'm seeing the webkit stuff I put in is still necessary…seems like some things must not be calling react-style-normalizer. But maybe I have things wired up improperly?

**Comment by jhopper28** [comment]
@natew What's your plan to merge this so it's installed with the default package?

**Comment by natew** [comment]
All merged

**Pull request merged**
